#################################### 
###### Row Similarity Search
#################################### 
row_similarity_search_datasets: # comment out the datasets you do not want to evaluate on
  - Amazon-Google # 4589 rows, 4 columns
  - Beer # 7345 rows, 5 columns
  - DBLP-ACM # 4910 rows, 5 columns
  - DBLP-GoogleScholar # 66879 rows, 5 columns
  - Fodors-Zagats # 864 rows, 7 columns
  - geological-settlements # 3054 rows, 8 columns
  - iTunes-Amazon # 62830 rows, 9 columns
  - MusicBrainz # 19375 rows, 10 columns 
  - Walmart-Amazon # 24628 rows, 6 columns

################################### 
##### Embeddings More Similar Than
###################################
more_similar_than_datasets:
  - wikidata_books
  - wikidata_books@no_genre   
  - wikidata_books@only_five_cols
  - wikidata_books@no_col_names
  - wikidata_books@no_pid_in_col_names
  - astronomical_objects
  - astronomical_objects@only-text

####################################
###### Column Similarity Search
####################################
column_similarity_search_datasets: # comment out the datasets you do not want to evaluate on
  - wikijoin_small 
  - valentine
  - opendata
  - autojoin
  - nextia

#################################### 
###### Cell Level Task
#################################### 
cell_task_datasets:
  - s2abel@clean
  - s2abel@dirty

####################################
###### Table Retrieval
####################################
table_retrieval_datasets:
  - fetaqa # 2003 tables, 2003 queries
  - tabfact # 1695 tables, 12779 queries
  - ottqa # 789 tables, 2114 queries
  - spider-train # 795 tables, 6997 queries
  - spider-validation # 81 tables, 1034 queries
  - spider-test # 180 tables, 2147 queries
  - bird-validation # 75 tables, 1534 queries

################################### 
##### Predictive ML
################################### 
predictive_ml_datasets:
  #################################### 
  ## Binary-classification (contain string columns)
  #################################### 
  - credit-g  # 1000 rows, 20 columns, [13/20] categorical
  - Fitness_Club  # 1500 rows, 6 columns, [3/6] categorical
  - Is-this-a-good-customer  # 1723 rows, 13 columns, [8/13] categorical
  - Marketing_Campaign  # 2240 rows, 25 columns, [8/25] categorical
  - seismic-bumps  # 2584 rows, 15 columns, [3/15] categorical
  - coil2000_insurance_policies  # 9822 rows, 85 columns, [3/85] categorical
  - Bank_Customer_Churn  # 10000 rows, 10 columns, [4/10] categorical
  - E-CommereShippingData  # 10999 rows, 10 columns, [4/10] categorical
  - online_shoppers_intention  # 12330 rows, 17 columns, [6/17] categorical
  - in_vehicle_coupon_recommendation  # 12684 rows, 24 columns, [21/24] categorical
  - HR_Analytics_Job_Change_of_Data_Scientists  # 19158 rows, 12 columns, [9/12] categorical
  - bank-marketing  # 45211 rows, 13 columns, [7/13] categorical
  - kddcup09_appetency  # 50000 rows, 212 columns, [38/212] categorical
  - Diabetes130US  # 71518 rows, 47 columns, [39/47] categorical
  - customer_satisfaction_in_airline  # 129880 rows, 21 columns, [16/21] categorical
  #################################### 
  ## Binary-classification (contain categorical but no string columns)
  #################################### 
  - blood-transfusion-service-center  # 748 rows, 4 columns, [0/4] categorical
  - diabetes  # 768 rows, 8 columns, [0/8] categorical
  - qsar-biodeg  # 1054 rows, 41 columns, [5/41] categorical
  - hazelnut-spread-contaminant-detection  # 2400 rows, 30 columns, [0/30] categorical
  - Bioresponse  # 3751 rows, 1776 columns, [0/1776] categorical
  - churn  # 5000 rows, 19 columns, [4/19] categorical
  - polish_companies_bankruptcy  # 5910 rows, 64 columns, [0/64] categorical
  - taiwanese_bankruptcy_prediction  # 6819 rows, 94 columns, [0/94] categorical
  - NATICUSdroid  # 7491 rows, 86 columns, [86/86] categorical
  - heloc  # 10459 rows, 23 columns, [0/23] categorical
  - jm1  # 10885 rows, 21 columns, [0/21] categorical
  - credit_card_clients_default  # 30000 rows, 23 columns, [3/23] categorical
  - Amazon_employee_access  # 32769 rows, 9 columns, [9/9] categorical
  - APSFailure  # 76000 rows, 170 columns, [0/170] categorical
  - GiveMeSomeCredit  # 150000 rows, 10 columns, [0/10] categorical
  #################################### 
  ## Multi-class Classification (contain string columns) [x/y] columns are categorical
  #################################### 
  - anneal  # 898 rows, 38 columns, num_classes=5 [32/38] categorical
  - website_phishing  # 1353 rows, 9 columns, num_classes=3 [9/9] categorical
  - splice  # 3190 rows, 60 columns, num_classes=3 [60/60] categorical
  - students_dropout_and_academic_success  # 4424 rows, 36 columns, num_classes=3 [17/36] categorical
  #################################### 
  ## Multi-class Classification (do not contain string columns) [x/y] columns are categorical
  #################################### 
  - maternal_health_risk  # 1014 rows, 6 columns, num_classes=3 [0/6] categorical
  - MIC  # 1699 rows, 111 columns, num_classes=8 [94/111] categorical
  - hiva_agnostic  # 3845 rows, 1617 columns, num_classes=3 [1617/1617] categorical
  - SDSS17  # 78053 rows, 11 columns, num_classes=3 [2/11] categorical 
  #################################### 
  ## Regression (contain string columns)
  #################################### 
  - healthcare_insurance_expenses  # 1338 rows, 6 columns, [3/6] categorical
  - Another-Dataset-on-used-Fiat-500  # 1538 rows, 7 columns, [1/7] categorical
  - wine_quality  # 6497 rows, 12 columns, [1/12] categorical
  - Food_Delivery_Time  # 45451 rows, 9 columns, [3/9] categorical
  - diamonds  # 53940 rows, 9 columns, [3/9] categorical
  #################################### 
  ## Regression (do not contain string columns)
  ####################################  
  - QSAR_fish_toxicity  # 907 rows, 6 columns, [0/6] categorical
  - concrete_compressive_strength  # 1030 rows, 8 columns, [0/8] categorical
  - airfoil_self_noise  # 1503 rows, 5 columns, [1/5] categorical
  - QSAR-TID-11  # 5742 rows, 1024 columns, [0/1024] categorical
  - miami_housing  # 13776 rows, 15 columns, [1/15] categorical
  - houses  # 20640 rows, 8 columns, [0/8] categorical
  - superconductivity  # 21263 rows, 81 columns, [0/81] categorical
  - physiochemical_protein  # 45730 rows, 9 columns, [0/9] categorical